### PR TITLE
updates to work on WIndows

### PR DESCRIPTION
**Pull request by csells**

### CODE REVIEW

**Comment by pq** [comment]
It looks like you'll want to re-format:

https://travis-ci.org/pq/surveyor/jobs/610374874?utm_medium=notification&utm_source=github_status.

**Comment by csells** [comment]
I don't see any output that says what reformatting needs to be applied. How do I find out?

**Comment by pq** [comment]
It's just a matter of running `dartftmt`.

FWIW here's where we check on the bot:

https://github.com/pq/surveyor/blob/aba994112f5028f9f618450a6c74a2bbd540711e/tool/travis.sh#L13

**Comment by pq** [comment]
(Unfortunately I'm not seeing any verbose options for `dartfmt`...)

**Pull request merged**
